// Dados mock para o app Receitas Premium
import { Recipe } from './types';

export const mockRecipes: Recipe[] = [
  {
    id: '1',
    title: 'Carbonara Autêntica',
    description: 'Receita tradicional italiana com guanciale e pecorino romano',
    category: 'massas',
    image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800&h=600&fit=crop',
    prepTime: 30,
    difficulty: 'médio',
    isPremium: false,
    rating: 4.8,
    ingredients: ['400g espaguete', '200g guanciale', '4 ovos', '100g pecorino romano', 'Pimenta preta'],
    instructions: ['Cozinhe o espaguete', 'Frite o guanciale', 'Misture ovos e queijo', 'Combine tudo'],
    author: 'Chef Marco',
    createdAt: '2024-01-15'
  },
  {
    id: '2',
    title: 'Picanha na Brasa Premium',
    description: 'Técnica profissional de preparo com temperos especiais',
    category: 'carnes',
    image: 'https://images.unsplash.com/photo-1558030006-450675393462?w=800&h=600&fit=crop',
    prepTime: 45,
    difficulty: 'médio',
    isPremium: true,
    rating: 4.9,
    ingredients: ['1kg picanha', 'Sal grosso', 'Alho', 'Chimichurri'],
    instructions: ['Tempere a carne', 'Prepare a brasa', 'Asse no ponto', 'Deixe descansar'],
    author: 'Chef Roberto',
    createdAt: '2024-01-20'
  },
  {
    id: '3',
    title: 'Tiramisù Clássico',
    description: 'Sobremesa italiana com café e mascarpone',
    category: 'sobremesas',
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800&h=600&fit=crop',
    prepTime: 40,
    difficulty: 'fácil',
    isPremium: false,
    rating: 4.7,
    ingredients: ['Mascarpone', 'Café expresso', 'Biscoitos champagne', 'Cacau em pó', 'Ovos'],
    instructions: ['Prepare o creme', 'Molhe os biscoitos', 'Monte em camadas', 'Refrigere'],
    author: 'Chef Sofia',
    createdAt: '2024-01-18'
  },
  {
    id: '4',
    title: 'Buddha Bowl Completo',
    description: 'Bowl nutritivo com quinoa, legumes e tahine',
    category: 'vegetariano',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&h=600&fit=crop',
    prepTime: 35,
    difficulty: 'fácil',
    isPremium: true,
    rating: 4.6,
    ingredients: ['Quinoa', 'Grão de bico', 'Abacate', 'Vegetais variados', 'Tahine'],
    instructions: ['Cozinhe a quinoa', 'Asse o grão de bico', 'Prepare os vegetais', 'Monte o bowl'],
    author: 'Chef Ana',
    createdAt: '2024-01-22'
  },
  {
    id: '5',
    title: 'Frango Grelhado Fitness',
    description: 'Receita low carb com marinada especial',
    category: 'fitness',
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800&h=600&fit=crop',
    prepTime: 25,
    difficulty: 'fácil',
    isPremium: false,
    rating: 4.5,
    ingredients: ['Peito de frango', 'Limão', 'Alho', 'Ervas finas', 'Azeite'],
    instructions: ['Marine o frango', 'Aqueça a grelha', 'Grelhe 6min cada lado', 'Sirva quente'],
    author: 'Chef Lucas',
    createdAt: '2024-01-25'
  },
  {
    id: '6',
    title: 'Smoothie Detox Verde',
    description: 'Bebida energizante com superalimentos',
    category: 'bebidas',
    image: 'https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=800&h=600&fit=crop',
    prepTime: 10,
    difficulty: 'fácil',
    isPremium: true,
    rating: 4.4,
    ingredients: ['Espinafre', 'Banana', 'Gengibre', 'Água de coco', 'Chia'],
    instructions: ['Lave os ingredientes', 'Bata no liquidificador', 'Adicione gelo', 'Sirva imediatamente'],
    author: 'Chef Marina',
    createdAt: '2024-01-28'
  },
  {
    id: '7',
    title: 'Risoto de Funghi Porcini',
    description: 'Risoto cremoso com cogumelos premium importados',
    category: 'massas',
    image: 'https://images.unsplash.com/photo-1476124369491-c4f9c6c6c8e2?w=800&h=600&fit=crop',
    prepTime: 50,
    difficulty: 'difícil',
    isPremium: true,
    rating: 4.9,
    ingredients: ['Arroz arbóreo', 'Funghi porcini', 'Vinho branco', 'Parmesão', 'Manteiga'],
    instructions: ['Hidrate os cogumelos', 'Refogue o arroz', 'Adicione caldo aos poucos', 'Finalize com manteiga'],
    author: 'Chef Marco',
    createdAt: '2024-01-30'
  },
  {
    id: '8',
    title: 'Brownie de Chocolate Belga',
    description: 'Brownie ultra cremoso com chocolate 70% cacau',
    category: 'sobremesas',
    image: 'https://images.unsplash.com/photo-1607920591413-4ec007e70023?w=800&h=600&fit=crop',
    prepTime: 45,
    difficulty: 'médio',
    isPremium: false,
    rating: 4.8,
    ingredients: ['Chocolate belga', 'Manteiga', 'Ovos', 'Açúcar', 'Farinha'],
    instructions: ['Derreta o chocolate', 'Misture ingredientes', 'Asse 25min', 'Deixe esfriar'],
    author: 'Chef Sofia',
    createdAt: '2024-02-01'
  }
];

export const categories = [
  { id: 'massas', label: 'Massas', icon: '🍝' },
  { id: 'carnes', label: 'Carnes', icon: '🥩' },
  { id: 'sobremesas', label: 'Sobremesas', icon: '🍰' },
  { id: 'vegetariano', label: 'Vegetariano', icon: '🥗' },
  { id: 'fitness', label: 'Fitness', icon: '💪' },
  { id: 'bebidas', label: 'Bebidas', icon: '🥤' },
];
